[package]
name = "cargo-rdme"
description = "Cargo command to create your `README.md` from your crate's documentation"
version = "0.0.0-pre"
authors = ["Diogo Sousa <diogogsousa@gmail.com>"]

edition = "2018"

homepage = "https://github.com/orium/cargo-rdme"
repository = "https://github.com/orium/cargo-rdme"
documentation = "https://docs.rs/cargo-rdme"
readme = "README.md"

keywords = [
    "readme", "cargo", "documentation"
]
categories = [
    "development-tools::cargo-plugins",
]

license = "MPL-2.0"

# What to include when packaging.
include = [
    "/src/**/*.rs",
    "/Cargo.toml",
    "/LICENSE.md",
    "/README.md",
    "/release-notes.md",
]

[badges]
codecov = { repository = "orium/cargo-rdme", branch = "master", service = "github" }

[dependencies]

[dev-dependencies]
pretty_assertions = "1.0"

[features]
fatal-warnings = []
